// Copyright The Conforma Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package asciidoc

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/conforma/cli/internal/documentation/asciidoc/cli"
	"github.com/conforma/cli/internal/documentation/asciidoc/rego"
	"github.com/conforma/cli/internal/documentation/asciidoc/tekton"
)

// GeneratedMarker is the comment placed at the top of generated Asciidoc files
// to distinguish them from handwritten documentation.
const GeneratedMarker = "// Generated by conforma CLI documentation tooling. DO NOT EDIT."

func GenerateAsciidoc(module string) error {
	var generated []string

	cliGenerated, err := cli.GenerateCommandLineDocumentation(module, GeneratedMarker)
	if err != nil {
		return err
	}
	generated = append(generated, cliGenerated...)

	regoGenerated, err := rego.GenerateRegoReference(module, GeneratedMarker)
	if err != nil {
		return err
	}
	generated = append(generated, regoGenerated...)

	tektonGenerated, err := tekton.GenerateTektonDocumentation(module, GeneratedMarker)
	if err != nil {
		return err
	}
	generated = append(generated, tektonGenerated...)

	if err := removeAbandonedPages(module, generated); err != nil {
		return err
	}

	return nil
}

// removeAbandonedPages removes generated Asciidoc page files that were not
// produced in the current generation run. A file is considered generated if its
// first line matches the GeneratedMarker. Handwritten files are left untouched.
func removeAbandonedPages(module string, generated []string) error {
	generatedSet := make(map[string]struct{}, len(generated))
	for _, p := range generated {
		generatedSet[p] = struct{}{}
	}

	pagesDir := filepath.Join(module, "pages")
	entries, err := os.ReadDir(pagesDir)
	if err != nil {
		return fmt.Errorf("reading pages directory %q: %w", pagesDir, err)
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".adoc") {
			continue
		}

		path := filepath.Join(pagesDir, entry.Name())
		if _, ok := generatedSet[path]; ok {
			// File was just generated, keep it.
			continue
		}

		isGenerated, err := hasGeneratedMarker(path)
		if err != nil {
			return fmt.Errorf("checking generated marker in %q: %w", path, err)
		}
		if !isGenerated {
			// Handwritten file, leave it alone.
			continue
		}

		if err := os.Remove(path); err != nil {
			return fmt.Errorf("removing abandoned file %q: %w", path, err)
		}
		fmt.Fprintf(os.Stderr, "Removed abandoned generated file: %s\n", path)
	}

	return nil
}


// hasGeneratedMarker reports whether the first line of the file matches
// GeneratedMarker.
func hasGeneratedMarker(path string) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return false, err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	if scanner.Scan() {
		return scanner.Text() == GeneratedMarker, nil
	}

	return false, scanner.Err()
}
